<<<<<<< HEAD
<<<<<<< HEAD
{"filter":false,"title":"routes.rb","tooltip":"/sample_app/config/routes.rb","undoManager":{"mark":2,"position":2,"stack":[[{"start":{"row":3,"column":26},"end":{"row":3,"column":27},"action":"remove","lines":["|"],"id":1}],[{"start":{"row":9,"column":22},"end":{"row":9,"column":23},"action":"insert","lines":["/"],"id":2},{"start":{"row":9,"column":23},"end":{"row":9,"column":24},"action":"insert","lines":["e"]},{"start":{"row":9,"column":24},"end":{"row":9,"column":25},"action":"insert","lines":["d"]},{"start":{"row":9,"column":25},"end":{"row":9,"column":26},"action":"insert","lines":["i"]},{"start":{"row":9,"column":26},"end":{"row":9,"column":27},"action":"insert","lines":["t"]}],[{"start":{"row":8,"column":24},"end":{"row":8,"column":25},"action":"remove","lines":["t"],"id":3},{"start":{"row":8,"column":23},"end":{"row":8,"column":24},"action":"remove","lines":["i"]},{"start":{"row":8,"column":22},"end":{"row":8,"column":23},"action":"remove","lines":["d"]}]]},"ace":{"folds":[],"scrolltop":0,"scrollleft":8.666666984558105,"selection":{"start":{"row":8,"column":22},"end":{"row":8,"column":22},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":0},"hash":"b830228ad1a4d7d1a1c5e45451341c28dd5cf9a3","timestamp":1603678230391}
=======
{"filter":false,"title":"routes.rb","tooltip":"/sample_app/config/routes.rb","undoManager":{"mark":2,"position":2,"stack":[[{"start":{"row":3,"column":26},"end":{"row":3,"column":27},"action":"remove","lines":["|"],"id":1}],[{"start":{"row":9,"column":22},"end":{"row":9,"column":23},"action":"insert","lines":["/"],"id":2},{"start":{"row":9,"column":23},"end":{"row":9,"column":24},"action":"insert","lines":["e"]},{"start":{"row":9,"column":24},"end":{"row":9,"column":25},"action":"insert","lines":["d"]},{"start":{"row":9,"column":25},"end":{"row":9,"column":26},"action":"insert","lines":["i"]},{"start":{"row":9,"column":26},"end":{"row":9,"column":27},"action":"insert","lines":["t"]}],[{"start":{"row":8,"column":24},"end":{"row":8,"column":25},"action":"remove","lines":["t"],"id":3},{"start":{"row":8,"column":23},"end":{"row":8,"column":24},"action":"remove","lines":["i"]},{"start":{"row":8,"column":22},"end":{"row":8,"column":23},"action":"remove","lines":["d"]}]]},"ace":{"folds":[],"scrolltop":0,"scrollleft":8.666666984558105,"selection":{"start":{"row":8,"column":22},"end":{"row":8,"column":22},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":0},"timestamp":1603678230283,"hash":"b830228ad1a4d7d1a1c5e45451341c28dd5cf9a3"}
>>>>>>> origin/master
=======
{"filter":false,"title":"routes.rb","tooltip":"/sample_app/config/routes.rb","undoManager":{"mark":2,"position":2,"stack":[[{"start":{"row":3,"column":26},"end":{"row":3,"column":27},"action":"remove","lines":["|"],"id":1}],[{"start":{"row":9,"column":22},"end":{"row":9,"column":23},"action":"insert","lines":["/"],"id":2},{"start":{"row":9,"column":23},"end":{"row":9,"column":24},"action":"insert","lines":["e"]},{"start":{"row":9,"column":24},"end":{"row":9,"column":25},"action":"insert","lines":["d"]},{"start":{"row":9,"column":25},"end":{"row":9,"column":26},"action":"insert","lines":["i"]},{"start":{"row":9,"column":26},"end":{"row":9,"column":27},"action":"insert","lines":["t"]}],[{"start":{"row":8,"column":24},"end":{"row":8,"column":25},"action":"remove","lines":["t"],"id":3},{"start":{"row":8,"column":23},"end":{"row":8,"column":24},"action":"remove","lines":["i"]},{"start":{"row":8,"column":22},"end":{"row":8,"column":23},"action":"remove","lines":["d"]}]]},"ace":{"folds":[],"scrolltop":0,"scrollleft":8.666666984558105,"selection":{"start":{"row":8,"column":22},"end":{"row":8,"column":22},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":0},"timestamp":1603678230283,"hash":"b830228ad1a4d7d1a1c5e45451341c28dd5cf9a3"}
>>>>>>> origin/master
